version: 2
updates:
  # Enable version updates for library itself.
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory.
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typedoc-plugin-markdown"
        update-types: ["version-update:semver-major"]
    groups:
      internal-tooling:
        patterns:
          - "@inrupt/internal-*"
          - "@inrupt/jest-*"
          - "@inrupt/eslint-*"
      external-types:
        patterns:
          - "@types/*"

  # Enable version updates for the website tooling.
  - package-ecosystem: "pip"
    # Look for `package.json` and `lock` files in the `root` directory.
    directory: "/docs"
    schedule:
      interval: "weekly"

  # Enable version updates for our CI tooling.
  - package-ecosystem: "github-actions"
    # For GitHub Actions, setting the directory to / will check for workflow
    # files in .github/workflows.
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for embedded tests and demo app
  - package-ecosystem: "npm"
    # Look for `package.json` and `package-lock.json` files in the `e2e/browser/test-app` and `examples` directories.
    directories:
      - "/e2e/browser/test-app"
      - "/examples"
    schedule:
      interval: "weekly"
    groups:
      internal-tooling:
        patterns:
          - "@inrupt/internal-*"
          - "@inrupt/jest-*"
          - "@inrupt/eslint-*"
      external-types:
        patterns:
          - "@types/*"
