name: End-to-end browser-based tests

on:
  push:

env:
  CI: true
jobs:
  e2e-browser:
    # Dependabot cannot access secrets, so it doesn't have a token to authenticate to ESS.
    # Since all the other jobs of this workflow depend on this one, skipping it should
    # skip the entire workflow.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ${{ matrix.os }}
    environment:
      name: ${{ matrix.environment-name }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
        # NSS does not support static client registration, which we rely on for testing.
        environment-name: ["ESS Dev-Next"]
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2.1.7
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ runner.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - run: npx playwright install
      - run: npm run test:e2e:browser:build
      - run: npm run test:e2e:browser
        env:
          E2E_TEST_ENVIRONMENT: ${{ matrix.environment-name }}
          E2E_TEST_UI_LOGIN: ${{ secrets.E2E_TEST_UI_LOGIN }}
          E2E_TEST_UI_PASSWORD: ${{ secrets.E2E_TEST_UI_PASSWORD }}
      - name: Archive browser-based end-to-end test failure screenshots, if any
        uses: actions/upload-artifact@v2.3.1
        continue-on-error: true
        if: failure()
        with:
          name: e2e-browser-failures
          path: e2e-browser-failures
      - name: Archive browser-based end-to-end test request logs
        uses: actions/upload-artifact@v2.3.1
        continue-on-error: true
        with:
          name: playwright-output
          path: test-results/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2.3.1
        continue-on-error: true
        with:
          name: code-coverage-report
          path: coverage
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2.3.1
        continue-on-error: true
        with:
          name: dist
          path: dist
