name: End-to-end Tests (Browser)

on:
  push:
  workflow_dispatch:

env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{github.event.deployment_status.state == 'success'}}
    if: github.actor != 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - name: Cache node modules
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node${{ runner.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm run build
    # Ideally, we'd autodetect installed browsers and run them headlessly.
    # See https://github.com/DevExpress/testcafe/issues/5641
    - name: Prepare browser-based end-to-end tests
      run: |
        cd .codesandbox/sandbox
        npm install
        # Run the end-to-end tests against the code in this branch specifically:
        npm install ../../
        cd ../../
    - name: Run browser-based end-to-end tests (Linux)
      # TODO: Add Edge/merge with Windows setup once Edge is available on Linux:
      run: npm run e2e-test-browser -- firefox:headless,chrome:headless
      env:
        E2E_TEST_ESS_NOTIFICATION_GATEWAY: ${{secrets.E2E_TEST_ESS_PROD_NOTIFICATION_GATEWAY}}
        E2E_TEST_ESS_IDP_URL: ${{ secrets.E2E_TEST_ESS_PROD_IDP_URL }}
        E2E_TEST_ESS_POD: ${{ secrets.E2E_TEST_ESS_PROD_POD }}
        E2E_TEST_ESS_COGNITO_USER: ${{ secrets.E2E_TEST_ESS_PROD_COGNITO_USER }}
        E2E_TEST_ESS_COGNITO_PASSWORD: ${{ secrets.E2E_TEST_ESS_PROD_COGNITO_PASSWORD }}
