name: End-to-end browser-based tests

on:
  push:

env:
  CI: true
jobs:
  e2e-browser:
    # Dependabot cannot access secrets, so it doesn't have a token to authenticate to ESS.
    # Since all the other jobs of this workflow depend on this one, skipping it should
    # skip the entire workflow.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment-name }}
    strategy:
      matrix:
        # NSS does not support static client registration, which we rely on for testing.
        environment-name: ["ESS Dev-Next"]
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run build
      # This is required to install some dependencies on the host system, in particular for WebKit
      - run: npx playwright install-deps
      - run: npx playwright install
      - run: npm run test:e2e:browser:build
      - run: npm run test:e2e:browser
        env:
          E2E_TEST_ENVIRONMENT: ${{ matrix.environment-name }}
          E2E_TEST_UI_LOGIN: ${{ secrets.E2E_TEST_UI_LOGIN }}
          E2E_TEST_UI_PASSWORD: ${{ secrets.E2E_TEST_UI_PASSWORD }}
      - name: Archive browser-based end-to-end test request logs
        uses: actions/upload-artifact@v2.3.1
        if: failure()
        continue-on-error: true
        with:
          name: playwright-output
          path: test-results/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2.3.1
        continue-on-error: true
        with:
          name: dist
          path: dist
