name: Publish website

on:
  push:
    branches:
      - main

env:
  CI: true
jobs:
  publish-website:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Prepare for publication to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Build API docs
        run: |
          npm ci
          npm run build-api-docs
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          cd docs/api/
          pip install -r requirements.txt
      - name: Build website
        run: |
          npm run build-docs-preview-site
          touch docs/dist/.nojekyll
      - name: Deploy to GitHub Pages
        run: ./publish-website.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
